AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  LandingTooManyErrorsAlarmArn:
    Type: String
    Description: ARN of distribution too many errors alarm

  LandingTooManyRequestsAlarmArn:
    Type: String
    Description: ARN of distribution too many requests alarm

Resources:
  # Dashboard
  FrontendMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}"
        AlarmArns: !Join
          - ','
          - - !Ref LandingTooManyErrorsAlarmArn
            - !Ref LandingTooManyRequestsAlarmArn
